### ISSUE TITLE
ld: duplicate symbol

### ISSUE THREAD

**Issue by banni** [ethz-asl/libpointmatcher#2]
received an error during compiling:

ld: duplicate symbol PointMatcher<float>::TransformFeatures::description()   in libpointmatcher.a(Transformations.cpp.o) and libpointmatcher.a(Core.cpp.o) for architecture x86_64
collect2: ld returned 1 exit status
make[2]: **\* [align_sequence] Error 1
make[1]: **\* [CMakeFiles/align_sequence.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
ld: duplicate symbol PointMatcher<float>::IdentityDataPointsFilter::description()   in libpointmatcher.a(DataPointsFilters.cpp.o) and libpointmatcher.a(Core.cpp.o) for architecture x86_64
collect2: ld returned 1 exit status
make[2]: **\* [convertCSVtoVTK] Error 1
make[1]: **\* [CMakeFiles/convertCSVtoVTK.dir/all] Error 2
make: **\* [all] Error 2

**Comment by johnyf** [comment]
For posterity, MacPorts `binutils` doesn't appear to include the GNU `ld` at all, as discussed [here](http://stackoverflow.com/questions/1608009/how-to-install-gnu-ld-on-mac-os-x-10-6), neither does MacPorts offer the GNU `ld` in any other way, as mentioned [here](http://stackoverflow.com/questions/9260504/macports-installing-binutils).

**Comment by pomerlef** [comment]
Does your comment requires any action on our side?

**Comment by ahundt** [comment]
on os x it is `otool -L` instead of ldd for debugging that type of problem

**Comment by ahundt** [comment]
On OS X, clang does the linking (when clang is being used), I think [g++ does the linking as well on OS X](https://stackoverflow.com/questions/6737738/gcc-on-mac-os-x-how-to-link-libraries-installed-with-macports)

**Comment by johnyf** [comment]
@pomerlef: No, I was actually trying to compile `z3`, but found this issue, so I commented here, because the finding happens to answer the [comment above](https://github.com/ethz-asl/libpointmatcher/issues/2#issuecomment-2284615) about the GNU `ld` on OS X (which doesn't exist). Thanks though.

@ahundt: With `clang`, the compilation of `z3` succeeds. However, it fails when using the `gcc` that ships with MacPorts. That `gcc` (`g++` too) does *not* do the linking, but invokes the system's `ld`, as commented [under this](http://stackoverflow.com/a/1618666/1959808) answer, which was linked to [above](https://github.com/ethz-asl/libpointmatcher/issues/2#issuecomment-161901596).

From [MacPorts issue 24471](http://trac.macports.org/ticket/24471) it appears that the GNU `ld` has not been ported to OS X, as answered by another question linked to from [above](https://github.com/ethz-asl/libpointmatcher/issues/2#issuecomment-161901596).
