### ISSUE TITLE
Problem in point cloud positioning with the Introduction to ICP

### ISSUE THREAD

**Issue by dydis** [ethz-asl/libpointmatcher#214]
Hi,
I am following the introduction to [ICP tutorial](http://libpointmatcher.readthedocs.io/en/latest/ICPIntro/). After running _pmicp_ with the default config file (found in examples/icp_tutorial/icp_tutorial_cfg.yaml), I noticed (in Paraview) that my reference point cloud (cloud_0.vtk) is not on the same coordinates as the reference point cloud generated by the algorithm (vissteps-reference). **Attached a screenshot of the problem**.
Can you please help me understand the problem?
![libpointmatcher](https://user-images.githubusercontent.com/7511086/26885373-c04a00be-4ba2-11e7-9b93-5b9ec75d115a.PNG)

**Comment by pomerlef** [comment]
Great question. Quick answer, it's normal.

The output given by the vtk inspector (visstep) is an internal view of what's going on inside the iterative process. We translate both point clouds to have the origin of the reference point cloud to its center of masse. We do that because we solve the rotation error around the origin and some point clouds (terrestrial survey, for example) use global coordinates with the origin being excessively far away. We do the transformation inverse before outputting the final transformation.

In your case, this means that cloud*.vtk are coherent together and visstep*.vtk are in a different frame but coherent together.

**Comment by dydis** [comment]
I get it. Thank you for your help.
