### ISSUE TITLE
Can you perform the actual transform on a point cloud with pmicp?

### ISSUE THREAD

**Issue by nickponline** [ethz-asl/libpointmatcher#224]
The `pmicp` binary can output the transform given two point clouds as CSVs. But is it possible perform the transform on the second point cloud so it's registered with the reference one.  Currently it only seem to generate a sample `in`, `out` and `reference` .VTK files?

**Comment by pomerlef** [comment]
I'm not sure what you're looking for. The file `test_data_out.vtk` should be your point cloud with the correction. 

If it's a problem of output format, and you wish to have CSV files instead of VTK, change the extension for those three lines in the source code:
https://github.com/ethz-asl/libpointmatcher/blob/master/examples/icp.cpp#L155

Recall that 'pmicp' is just an example for the library.

**Comment by nickponline** [comment]
Thanks
