### ISSUE TITLE
Is that possible to achieve good ICP alignment in this situation? 

### ISSUE THREAD

**Issue by bxc237** [ethz-asl/libpointmatcher#309]
Hi,
Could anyone help me to check this alignment problem?
The point cloud was captured by a VLP-16 in a big lab.
The white points are the reference points (the whole lab), red points are the input points (just a part of the lab) and green points are the aligned points after performed ICP. As shown in the picture, the aligned points are totally wrong (the correct alignment should be rotating the red points clockwise), ICP even downscaled the input points. The video of the ICP alignment is in this link (https://youtu.be/2qAyTu_a6Sc), please take a look.
![496240024](https://user-images.githubusercontent.com/16990429/50441398-773e5080-0935-11e9-9f63-9cb2a5e7b32a.jpg)
I do not think the input point cloud is too far away from the reference one and the rotation is not that large. The matcher should be capable to correctly aligned those points, right? 
I would be most grateful if anyone might be able to give me some advice. THX!!

**Comment by bxc237** [comment]
Hi, @PhiBabin, please go to this link https://www.dropbox.com/sh/9uwnec8jlbc88lo/AACbUgGGottcGodlIHjUmKnpa?dl=0, which includes yaml, read and reference csv, so that you can reproduce this problem in libpointmatcher. Thanks....

**Comment by PhiBabin** [comment]
It seems I was mistaken, there is a minimizer that support a minimization with translation+rotation+scale. You are using `PointToPointSimilarityErrorMinimizer` which can scale the point cloud. Since your point cloud don't seem to require rescaling, I would suggest using `PointToPointErrorMinimizer` or even better `PointToPlaneErrorMinimizer`.

**Comment by simonpierredeschenes** [comment]
It looks like the problem is that the distance between the reference and the reading is too important. By specifying an initial rotation of -45 degrees about the y axis, I managed to get a good alignment:
```
pmicp --initRotation [0.707,0,-0.707,0,1,0,0.707,0,0.707] --config default.yaml reference.csv read.csv
```

![screenshot from 2019-01-10 10-47-20](https://user-images.githubusercontent.com/25109638/50979955-9ad0d180-14c5-11e9-92c1-03a99114dc88.png)

**Comment by bxc237** [comment]
@simonpierredeschenes Thank you. I can also achieve a good result if the presumption of the relative translation between ref and read-in points cloud is given. However, it seems to be impossible to achieve good alignment without the presumption of rotation/translation. I will find a way to align them without the presumption and post here. Thank you both very much! @PhiBabin @simonpierredeschenes
