### ISSUE TITLE
Covariance estimation not working for 2D point cloud

### ISSUE THREAD

**Issue by dongjing3309** [ethz-asl/libpointmatcher#36]
Hi,

I have tried that both PointToPointWithCovErrorMinimizer and PointToPlaneWithCovErrorMinimizer cannot return correct Covariance Matrix, PointToPlaneWithCovErrorMinimizer simply return all zero matrix (also 6x6 matrix means the dimension not right), PointToPointWithCovErrorMinimizer will give below error

```
pmicp: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:114: Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::DenseCoeffsBase<Derived, 0>::Index, Eigen::DenseCoeffsBase<Derived, 0>::Index) const [with Derived = Eigen::Matrix<float, -1, -1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const float&; Eigen::DenseCoeffsBase<Derived, 0>::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
```

Thanks :)

**Comment by v01d** [comment]
@fjperezgrau could you provide further hints on what changes should be done? 
I don't really get why, if it works for 3D, it does not work on 2D since it would be a particular case of all points on a plane. Your help would be greatly appreciated since currently there's no way to know how good the results from ICP in each dimension.

**Comment by v01d** [comment]
I started looking at the code and I'm close to adapting it to 2D (although at the moment performing some unnecessary computations). I'm on the point-to-plane case. Main issue is that it expects a 3D normal. By changing that to allowing 2D normals it is only a matter (AFAIK) of supplying the projection of the 2D normal to 3D. 
Initially I've set 0 to the third coordinate of "normal", however this made the third row and column of the hessian zero and therefore it was non-inversible.
I've set it now to 1 and it returns a covariance matrix filled with values (not NaNs as before) but I'm unsure if it is correct to use 1.

To me, a 2D normal (x,y) should be represented as (x,y,0) on 3D, but this does not seem to make sense. 

Anyone could offer some help?

**Comment by fjperezgrau** [comment]
In the first thesis by Steinmann you can check Appendix A, it's the covariance of a minimization algorithm and you can see how it's done in 2D (for 3D it only provides some hints). The second thesis by de Candia has another Appendix A where it explains much better how it's done in 3D.
Hope this helps!

**Comment by v01d** [comment]
Hi,
I've read both PDFs, however my intention was to see if I could re-use the 3D version for the 2D version. I'm still not quite sure if it is possible or even reasonable. 
I think I will let someone else fix this as it is not as simple as I hoped.

**Comment by artivis** [comment]
Any update on this problem ??
Both links provided by @fjperezgrau are dead.

**Comment by pomerlef** [comment]
@davidlandry93 this might be up your alley...

**Comment by v01d** [comment]
Hi, on our lab we had a master student working on this as his thesis and he
modified libpointmatcher to include this functionality. He based his work
on the PDFs listed in this thread.
@tomifischer said he might be able to push this to github and make a PR.
I'm not sure about the state of the code but maybe someone else can polish
it for integration.

**Comment by pomerlef** [comment]
If the PR is not too invasive, it should be easy to review from our side.

**Comment by artivis** [comment]
Could anyone re-link the PDFs that @fjperezgrau provided ? The previous links are dead.

@v01d I might be able to help in polishing :+1:.

**Comment by pomerlef** [comment]
They migrated their website and part of the content were lost. Luckily, some contact could find copies:

[ICP Optimization for 3D Robot Mapping](https://github.com/ethz-asl/libpointmatcher/files/1254438/315-report.pdf)
[Analysis of Scan Matching Methods for Indoor 3D Mapping](https://github.com/ethz-asl/libpointmatcher/files/1254439/100-report.pdf)

**Comment by tomifischer** [comment]
Hi, as @v01d mentioned, a master student working at our lab added the PointToPlaneWithCovErrorMinimizer implementation to the libpointmatcher code based on the aforementioned papers. The covariance seemed to be working well, you can see the results in his [thesis](https://robotica.dc.uba.ar/wp-content/papercite-data/pdf/astepaniuk_tesis.pdf) (only in spanish though).
Since the work was completed some months ago, I just updated it to make it compile against the newest changes and sent a [pull request](https://github.com/ethz-asl/libpointmatcher/pull/220). Feel free to check out and comment on the code.
