### ISSUE TITLE
Could not compile in Xcode 6

### ISSUE THREAD

**Issue by jayden118** [ethz-asl/libpointmatcher#72]
Dear all,

I have compiled and intalled the libpointmatcher in my mac os machine successfully. However, I want to link to my current xcode projects and trying to compile the libpointmatcher project in xcode. I followed the instruction in advanced section but failed to compile the code in xcode. The errors are as follows:

![image](https://cloud.githubusercontent.com/assets/7490505/6592007/33185258-c80b-11e4-9bd8-3382f51d07cd.png)

May I know how to solve this issue? 

Thank you very much.

Regards,
Jayden

**Comment by pomerlef** [comment]
My guess is that your problem is related to #66. As a temporary fix, you can copy `libyaml-cpp-pm.a` in your install folder. In you case, you should be able to find the library in:
```
./libpointmatcher/build/contrib/yaml-cpp-pm
```
and your install folder [1]:
```
/usr/local/lib
```
[1] confirm that libpointmacher.a is there, I'm not sure where `make install` will send it in your case.

This would be a temporary fix, while we arrange the whole yaml dependency problem.

**Comment by jayden118** [comment]
Dear pomerlef,

Thank you very much. Now everything is working fine.

Cheers!

Regards,
Jayden
